language: objective-c
osx_image: xcode8
branches:
  only:
    - master
    - develop
before_install:
  - bundle install
script:
  - set -o pipefail
  - fastlane travis
  - danger --verbose
  - pod lib lint --quick
